### ISSUE TITLE
Using Nested Object In RefinementList 

### ISSUE THREAD

**Issue by britisharmy** [typesense/typesense-instantsearch-demo-no-npm-yarn#1]
I have this document

```
{
	"boosting_score": 1,
	"date_posted": "1675610976",
	"id": "63dfcb60c300c",
	"link_url": "0",
	"location": "New York",
	"post_id": "63dfcb60c300d",
	"post_status": "published",
	"price": 4000000,
	"region": "New York City",
	"search_data": "{\"files\":[{\"name\":\"images.jpeg\",\"size\":8188,\"url\":\"https://example.com/file_uploads/files/images.jpeg\",\"thumbnailUrl\":\"https://example.com/file_uploads/files/thumbnail/images.jpeg\",\"deleteUrl\":\"https://example.com/file_uploads/index.php?file=images.jpeg\",\"deleteType\":\"DELETE\"}],\"make\":\"Toyota\",\"model\":\"Land Cruiser Prado\",\"title\":\"PRADO TOYOTA\",\"region\":\"New York City\",\"location\":\"New York\",\"mileage\":30000,\"year_of_manufacture\":\"2015\",\"fuel_type\":\"CNG\",\"transmission\":\"Automatic\",\"engine_size\":3900,\"drive_train\":\"Rear Wheel\",\"registration_status\":\"Registered\",\"condition\":\"Brand New \",\"color\":\"Blue\",\"description\":\"Unique with class\",\"price\":4000000,\"carspackage\":\"Gold\",\"category\":\"Agriculture\",\"sub_category\":\"Farm Machinery\",\"token\":\"1662d3979fcb604b241610f9a72cdf1bbd64a83d2b955098a184045dd4bb2659\"}",
	"title": "PRADO TOYOTA",
	"user_id": "32"
}
```

and i want to use refinement list widget like

```
	instantsearch.widgets.refinementList({
		  container: '#refinement-list',
		  attribute: 'search_data.make',
	}),
```

I get this error

`Error: 404 - Could not find a facet field named `search_data.make` in the schema.`

and this error

`TypesenseInstantsearchAdapter.js:86 Uncaught (in promise) Error: 404 - Could not find a facet field named `search_data.make` in the schema.`

I am using this files

```
 <script src="https://cdn.jsdelivr.net/npm/instantsearch.js@4.44.0"></script>
<script src="https://cdn.jsdelivr.net/npm/typesense-instantsearch-adapter@2/dist/typesense-instantsearch-adapter.min.js"></script>
```

i am using typesense ` typesense-server-0.24.0-amd64.deb`

This is the entire code

```
mounted(){
		const typesenseInstantsearchAdapter = new TypesenseInstantSearchAdapter({
        server: {
            apiKey: '', // Be sure to use an API key that only allows searches, in production
            nodes: [
                {
                    host: '',
                    port: '8108',
                    protocol: 'https',
                },
            ],
        },
       
        additionalSearchParameters: {
            query_by: "title,region,location,search_data",
        },
    });
    const searchClient = typesenseInstantsearchAdapter.searchClient;

    const search = instantsearch({
        searchClient,
        indexName: 'main_search',
    });


		
    search.addWidgets([
        instantsearch.widgets.searchBox({
            container: '#searchbox',
        }),
        instantsearch.widgets.configure({
            hitsPerPage: 8,
        }),
		
		instantsearch.widgets.refinementList({
		  container: '#refinement-list',
		  attribute: 'search_data.make',
		}),
		
		instantsearch.widgets.hits({
            container: '#hits',
            templates: {
                item(item) {
				console.log('Item', item)
				
				let search_data = JSON.parse(item.search_data);
                    return `
                        <div>
                          <div class="big_font"><img src="${search_data.files[0].url}" style="width:100%" /></div>
                          <div class="big_font" style="font-weight:bold">${item.title}</div>
                          <div class="big_font" style="font-weight:bold">Ksh ${item.price}</div>
                        </div>
                      `;
                },
            },
        }),
        instantsearch.widgets.pagination({
            container: '#pagination',
        }),
    ]);

    search.start();
	},
	 data() {
    return {
      
    };
  },
```

**Comment by jasonbosco** [comment]
Looks like `search_data` is set as a JSON string in the document. It needs to be a proper nested object and not a string, for the nested fields feature to work. 

So you want to set `search_data` as type `object` in the collection schema, and then just before inserting the document into Typesense, you want to JSON-parse the `search_data` string.

**Comment by britisharmy** [comment]
You mean i change from 

```
[
      'name'  => 'search_data',
      'type'  => 'auto',
	  'facet' => true
    ], 	
```

to 

```
[
      'name'  => 'search_data',
      'type'  => 'object',
	  'facet' => true
    ], 	
```

**Comment by jasonbosco** [comment]
You can leave that to `auto`, but then you need to change the data type of that field when you generate these documents at indexing time, to use an object instead of converting it to a JSON string.

**Comment by britisharmy** [comment]
Okay. Thanks, i will give it a try.

**Comment by britisharmy** [comment]
This is the data i am getting from the client

`{"files":[{"name":"Acoustic-Guitars (1).jpg","size":8829,"url":"https://example.com/file_uploads/files/Acoustic-Guitars%20%281%29.jpg","thumbnailUrl":"https://example.com/file_uploads/files/thumbnail/Acoustic-Guitars%20%281%29.jpg","deleteUrl":"https://example.com/file_uploads/index.php?file=Acoustic-Guitars%20%281%29.jpg","deleteType":"DELETE"},{"name":"Adapters.jpg","size":3069,"url":"https://example.com/file_uploads/files/Adapters.jpg","thumbnailUrl":"https://example.com/file_uploads/files/thumbnail/Adapters.jpg","deleteUrl":"https://example.com/file_uploads/index.php?file=Adapters.jpg","deleteType":"DELETE"},{"name":"acer.png","size":3319,"url":"https://example.com/file_uploads/files/acer.png","thumbnailUrl":"https://example.com/file_uploads/files/thumbnail/acer.png","deleteUrl":"https://example.com/file_uploads/index.php?file=acer.png","deleteType":"DELETE"},{"name":"Ashtrays (1).jpg","size":8167,"url":"https://example.com/file_uploads/files/Ashtrays%20%281%29.jpg","thumbnailUrl":"https://example.com/file_uploads/files/thumbnail/Ashtrays%20%281%29.jpg","deleteUrl":"https://example.com/file_uploads/index.php?file=Ashtrays%20%281%29.jpg","deleteType":"DELETE"}],"make":"Toyota","model":"Belta","title":"A good car","region":"Queens","location":"New York City","mileage":254000,"year_of_manufacture":"1950","fuel_type":"CNG","transmission":"Automatic","engine_size":2000,"drive_train":"All Wheel","registration_status":"Not Registered","condition":"Brand New   ","color":"Beige","description":"A very good car","price":250000,"carspackage":"Top 30","category":"Vehicles","sub_category":"Cars","token":"216a54cc80e20db65079b41392fbfbe4be55acec0fc6d69a96b6e08ed3a4a9f8"}`

I am receiving it like this 

```
	$raw_data = file_get_contents('php://input');
	$data = json_decode($raw_data, true);
```

and creating the document like this

```
$document = [
		  'id'  => "$id",
		  'user_id'  => "$user_id",
		  'search_data' => json_decode($raw_data),
		  'post_id'  => "$post_id",
		  'title'  => "$title",
		  'price' => (int)$price,
		  'link_url'  => "$link_url",
		  'region'  => "$region",
		  'location' => "$location",
		  'boosting_score' => "$boosting_score",
		  'post_status' => "$post_status",
		  'date_posted' => "$date_posted"
		];

		$client->collections['main_search']->documents->create($document); 
```

I keep getting this error

`Idle timeout reached for "https://example.com:8108/collections/main_search/documents/".`

This is how i created my collection


```
$schema = [
    'name'      => 'main_search',
	'enable_nested_fields'=> true,
    'fields'    => [
    [
      'name'  => 'id',
      'type'  => 'string'
    ], 
    [
      'name'  => 'search_data',
      'type'  => 'auto',
	  'facet' => true
    ], 	
	[
      'name'  => 'user_id',
      'type'  => 'string'
    ],	
	[
      'name'  => 'post_id',
      'type'  => 'string'
    ],	
	[
      'name'  => 'title',
      'type'  => 'string',
	  'facet' => true
    ],	
	[
      'name'  => 'price',
      'type'  => 'int32',
	  'facet' => true
    ],	
	[
      'name'  => 'link_url',
      'type'  => 'string'
    ],	
	[
      'name'  => 'region',
      'type'  => 'string',
	  'facet' => true
    ],
	[
      'name'  => 'location',
      'type'  => 'string',
	  'facet' => true
    ],	
	[
      'name'  => 'boosting_score',
      'type'  => 'int32',
	  'facet' => true
    ],
	[
      'name'  => 'post_status',
      'type'  => 'string',
	  'facet' => true
    ],
	[
      'name'  => 'date_posted',
      'type'  => 'string',
	  'facet' => true
    ]
  ],
  'default_sorting_field' => 'price'
];

$client->collections->create($schema);
```

How can i use the object as advised?

**Comment by britisharmy** [comment]
I got it working without changing much of my code above. 

`'search_data' => json_decode($raw_data),`

The problem was with my host digitalocean. For $200 a month for my servers they were throttling my speed and access to my own server speeds so i moved to aws. I am not burying their service since if it works for you, then go for it.  AWS Lightsail  costs are well shown here https://lightsail.aws.amazon.com/ls/docs/en_us/articles/amazon-lightsail-frequently-asked-questions-faq#lightsail-faq-data-transfer-charges

I had a droplet in Mumbai and aws special pricing is Asia Pacific (Mumbai) (ap-south-1): $0.13 USD/GB

Digitalocean is much smaller and this cost must apply to them as well so i believe that's why they are throttling speeds without alerting customers. 

I wouldn't recommend anyone host on digitalocean until they are upfront about bandwidth.
