### ISSUE TITLE
Refining or filtering on click

### ISSUE THREAD

**Issue by britisharmy** [typesense/typesense-instantsearch-demo-no-npm-yarn#2]
I have displayed my collection and the page is working well. However, i would like to allow my user to interact with the data by applying filters and clearing filters.

- search
- refinement list attribute
- price  i.e applying filters
- sort 
- clear filters

How can i apply filters and change an attribute on click? So far from the docs, i have seen this would work but i havent seen some working code

```
const { refine } = renderOptions;
	
$("#klik").click(function(){
     refine({ hitsPerPage: 4 });
});
```
How can i achieve the listed actions above on click?

**Comment by jasonbosco** [comment]
Here's how to do this: https://www.algolia.com/doc/guides/building-search-ui/going-further/access-state-outside-lifecycle/js/#refining-a-search-from-the-outside

**Comment by britisharmy** [comment]
I switched to vue js and it works perfectly with this widget

```
<ais-configure
	  :hits-per-page.camel="hpp_number"
	  :filters="car_model"
	/>
```
